# Generated by Django 6.0 on 2025-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
