# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_warning_sent_taskassignment_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknode',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
