# Generated by Django 6.0 on 2026-01-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tasknode_task_taskgroup_tasknode_parent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknode',
            name='parent_group',
        ),
        migrations.AlterField(
            model_name='tasknode',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.task'),
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
