# Generated by Django 6.0 on 2026-01-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_taskgroup_tasknode_parent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknode',
            name='parent_group',
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
