# Generated by Django 6.0 on 2026-01-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_tasknode_parent_group_delete_taskgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknode',
            name='is_pinned',
        ),
    ]
