# Generated by Django 6.0 on 2026-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_tasknode_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknode',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
