# Generated by Django 6.0 on 2026-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tasknode_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_task', 'Yeni Görev'), ('assignment', 'Görev Ataması'), ('task_completed', 'Görev Tamamlandı'), ('all_completed', 'Ekip Tamamladı'), ('file_uploaded', 'Dosya Yüklendi'), ('priority_changed', 'Öncelik Değişti'), ('new_comment', 'Yeni Yorum'), ('deadline', 'Süre Azaldı')], max_length=20),
        ),
    ]
