# Generated by Django 6.0 on 2026-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
