# Generated by Django 5.2.7 on 2026-02-22 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_notification_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('session_start', 'Oturum Başladı'), ('session_end', 'Oturum Bitti'), ('task_created', 'Görev Oluşturuldu'), ('task_moved', 'Görev Taşındı'), ('task_completed', 'Görev Tamamlandı'), ('comment_sent', 'Yorum Gönderildi'), ('file_uploaded', 'Dosya Yüklendi'), ('notification_opened', 'Bildirim Açıldı'), ('card_connected', 'Kart Bağlandı')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
