# Generated by Django 5.2.7 on 2026-02-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dönem Adı')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('tenants', models.ManyToManyField(blank=True, related_name='presentation_periods', to='core.tenant', verbose_name='Gruplar')),
            ],
            options={
                'verbose_name': 'Sunum Dönemi',
                'verbose_name_plural': 'Sunum Dönemleri',
            },
        ),
    ]
