# Generated by Django 5.2.7 on 2026-02-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Aşama Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Aşama Açıklaması')),
                ('order', models.IntegerField(verbose_name='Sıra')),
                ('is_final_stage', models.BooleanField(default=False, verbose_name='Final Aşaması mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Süreç Aşaması',
                'verbose_name_plural': 'Süreç Aşamaları',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='is_pipeline_task',
            field=models.BooleanField(default=False, verbose_name='Pipeline Görevi mi?'),
        ),
        migrations.AddField(
            model_name='task',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.pipelinestage'),
        ),
        migrations.CreateModel(
            name='PipelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taslak Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='core.presentationperiod', verbose_name='Sunum Dönemi')),
            ],
            options={
                'verbose_name': 'Süreç Taslağı',
                'verbose_name_plural': 'Süreç Taslakları',
            },
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.pipelinetemplate', verbose_name='Taslak'),
        ),
    ]
