# Generated by Django 5.2.7 on 2026-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pipelinestage_task_is_pipeline_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Şüpheli mi?'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='time_on_question_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soru Başında Geçen Süre (ms)'),
        ),
    ]
