# Generated by Django 5.2.7 on 2026-02-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_surveyresponse_is_suspicious_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_kanban',
            field=models.BooleanField(default=False, verbose_name='Kanban Arayüzü'),
        ),
    ]
