# Generated by Django 5.1.15 on 2026-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_task_parent_task_tenant_is_kanban'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tutorial_seen',
            field=models.BooleanField(default=False),
        ),
    ]
