# Generated by Django 5.1.15 on 2026-03-18 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_researchuseralias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Cihaz Kaydı', 'verbose_name_plural': 'Cihaz Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['order'], 'verbose_name': 'Aşama', 'verbose_name_plural': 'Aşamalar'},
        ),
        migrations.AlterModelOptions(
            name='pipelinetemplate',
            options={'verbose_name': 'Sunum Takvimi', 'verbose_name_plural': 'Sunum Takvimleri'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Araştırma Grubu', 'verbose_name_plural': 'Araştırma Grupları'},
        ),
        migrations.AlterField(
            model_name='device',
            name='hwid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cihaz ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Katılımcı Onayı'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_kanban',
            field=models.BooleanField(default=False, verbose_name='Arayüz Tipi (Kanban=True, Spiral=False)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Grup Kodu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='PipelineQualitativeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_questions', to='core.pipelinestage')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineQualitativeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipelinequalitativequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
